apiVersion: v1
kind: Secret
metadata:
  name: my-infra-manifests-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/HyeonWooJo/my-infra-manifests.git
  # 공개 레포지토리인 경우 username과 password는 필요 없습니다
  # 비공개 레포지토리인 경우 아래 주석을 해제하고 값을 설정하세요
  # username: <your-github-username>
  # password: <your-github-token>


